### DISCUSSION TITLE
Helm charts in helm repo do not match docs and charts in this repo

### DISCUSSION THREAD

**Discussion by johnynfulleffect** [Azure/api-management-self-hosted-gateway#67] [Q&A] [answered]
### Report

I have been working on getting this helm chart running in my AKS cluster, and I have been getting errors related to dapr.app.id, gateway.configuration.uri and gateway.auth.key.  Come to find out, I don't think [this](https://github.com/Azure/api-management-self-hosted-gateway/commit/06716209ec054fcddaca3050447cfbcd78fd11f8) commit has been published to the Helm repo.

### Expected Behavior

Using a values.yaml like explained in this repo should work without errors:

```
gateway:
  configuration:
    uri: testUri
  auth:
    key: testKey
dapr:
  enabled: true
  app:
    id: testId
  config: tracing
  logging:
    useJsonOutput: true
    level: info
```

### Actual Behavior

Only an older values.yaml will work:

```
gateway:
  endpoint: testUri
  authKey: testKey
dapr:
  enabled: true
  appId: testId
  config: tracing
  logging:
    useJsonOutput: true
    level: info
```

### Steps to Reproduce the Problem

1. use the values.yaml in this repo and deploy the helm chart

### Logs from self-hosted gateway

Helm output:
```
wait.go:244: [debug] Deployment is not ready: dapr-dev/dapr-gateway. 0 out of 1 expected pods are ready
```

Replica Set Event:
```
Error creating: admission webhook "sidecar-injector.dapr.io" denied the request: value for the dapr.io/app-id annotation is empty
```

Helm output:
```
Error: template: azure-api-management-gateway/templates/secret.yaml:12:44: executing "azure-api-management-gateway/templates/secret.yaml" at <b64enc>: invalid value; expected string
```

### Self-hosted Gateway Version

azure-api-management-gateway-0.3.0, helm chart version 1.1.2

### Deployment

Self-Managed (YAML/Helm)

### Platform

Microsoft Azure

### Kubernetes Version

1.19
