### ISSUE TITLE
Helm charts not respecting namespace when (helm template --namespace) is used to generate the manifests

### ISSUE THREAD

**Issue by midhun-mohan** [Azure/api-management-self-hosted-gateway#295]
### Report

The current helm charts for apim self hosted gateway doesn't respect using the `--namespace` flag when using the helm template command. Ideally, this should be respected.

### Expected Behavior

Helm template with `--namespace` flags generate resources with `.metadata.namespace` set

### Actual Behavior

The manifests are being generated without .metadata.namespace set when --namespace=<custom-namespace> is being used. 

### Steps to Reproduce the Problem

1. Run `helm repo add azure-apim-gateway https://azure.github.io/api-management-self-hosted-gateway/helm-charts/`

```
~  helm repo list | grep gateway
azure-apim-gateway 	https://azure.github.io/api-management-self-hosted-gateway/helm-charts/
```

2. Run `helm template --namespace=apim-gateway apim azure-apim-gateway/azure-api-management-gateway --set=gateway.auth.key=<gatewayAuthKey>--set gateway.configuration.uri=<gatewayConfigurationUri>
`
This generates manifests without `.metadata.namespace` being set. 

```
helm template --namespace=apim-gateway apim azure-apim-gateway/azure-api-management-gateway --set=gateway.auth.key=dddddd --set gateway.configuration.uri=wwwwwww | grep metadata -A 3
metadata:
  name: apim-azure-api-management-gateway
  labels:
    helm.sh/chart: azure-api-management-gateway-1.10.0
--
metadata:
  name: apim-azure-api-management-gateway
  labels:
    helm.sh/chart: azure-api-management-gateway-1.10.0
--
metadata:
  name: apim-azure-api-management-gateway
  labels:
    helm.sh/chart: azure-api-management-gateway-1.10.0
--
metadata:
  name: apim-azure-api-management-gateway-instance-discovery
  labels:
    helm.sh/chart: azure-api-management-gateway-1.10.0
--
metadata:
  name: apim-azure-api-management-gateway
  labels:
    helm.sh/chart: azure-api-management-gateway-1.10.0
--
metadata:
  name: apim-azure-api-management-gateway
  labels:
    helm.sh/chart: azure-api-management-gateway-1.10.0
--
    metadata:
      labels:
        app.kubernetes.io/name: apim-azure-api-management-gateway
        app.kubernetes.io/component: self-hosted-gateway
--
metadata:
  name: "apim-azure-api-management-gateway-test-connection"
  labels:
    app.kubernetes.io/name: azure-api-management-gateway
```

### Logs from self-hosted gateway

```
NA
```

### Self-hosted Gateway Version

v1.10.0

### Deployment

Self-Managed (YAML/Helm)

### Platform

None

### Kubernetes Version

None

### Anything else?

I can contribute with a PR if needed :
