### ISSUE TITLE
otel metrics not being sent

### ISSUE THREAD

**Issue by ecooke-macu** [Azure/api-management-self-hosted-gateway#338]
### Report

No requests being made to open telemetry collector even though it's turned on.

### Expected Behavior

Otel requests for metrics get sent to our collector

### Actual Behavior

No requests being made to open telemetry collector

### Steps to Reproduce the Problem

1. Create an open telemetry collector (or any nginx or something to monitor requests)
2. Monitor collector for requests
3. Set up the apim gateway with the below config map (yaml based setup).

```yaml
data:
  config.service.auth: azureAdApp
  config.service.auth.azureAd.authority: https://login.microsoftonline.com
  config.service.auth.azureAd.clientId: xxx
  config.service.auth.azureAd.tenantId: xxx
  config.service.endpoint: xxx.configuration.azure-api.net
  gateway.name: apim-macu-dev-gateway
  observability.opentelemetry.collector.uri: http://nrotel.devsecure.xxx
  observability.opentelemetry.enabled: "true"
  observability.opentelemetry.system-metrics.enabled: "true"
  telemetry.logs.std: json
  telemetry.logs.std.color: "false"
  telemetry.logs.std.level: all
  telemetry.metrics.cloud: "true"
```

### Logs from self-hosted gateway

This is a log entry that I found that appears periodically
```
{"level":"Verbose","timestamp":"2025-03-26T14:19:42.1984013Z"","eventType":"PushingTelemetryToApi","message":"uri: https://xxx.configuration.azure-api.net///gateways/xxx-gateway/telemetry, request-id: f65e2d0c-1ecd-4287-962a-058553b59b04, payload: {\"gateway\":{\"id\":\"apim-macu-dev-gateway\",\"version\":\"2.8.2992.0\",\"instance\":{\"id\":\"apim-macu-gateway-55c5df6d4c-974dg\",\"processorCount\":8}},\"runtime\":{\"authentication\":{\"type\":\"azureAdApp\",\"entraId\":{\"clientId\":\"xxx\",\"tenantId\":\"xxx\"},\"gatewayToken\":{\"expiry\":null}},\"configuration\":{\"lastEventId\":\"000092a7\",\"localBackup\":{\"enabled\":true,\"lastEventId\":null,\"location\":\"/apim/config\",\"compressedSizeInBytes\":null}},\"dapr\":{\"enabled\":false,\"appId\":\"n/a\",\"runtimeVersion\":\"n/a\"},\"metrics\":{\"openTelemetry\":{\"enabled\":true,\"uri\":\"http://nrotel.devsecure.xxx\"},\"statsD\":{\"enabled\":false,\"uri\":null,\"tagFormat\":\"DogStatsD\"},\"azureMonitor\":{\"enabled\":true}},\"logging\":{\"localProvider\":null},\"security\":{\"localCa\":{\"enabled\":false}}},\"infrastructure\":{\"arc\":{\"infra\":\"\",\"extensionName\":\"\",\"cluster\":{\"armResourceId\":\"\",\"region\":\"\"}},\"containerApps\":{\"name\":null,\"revisionName\":null},\"installation\":{\"mechanism\":\"custom\",\"artifact\":{\"source\":\"\",\"version\":\"\"}},\"orchestrator\":{\"type\":\"\",\"distribution\":\"\"},\"kubernetes\":{\"ingressEnabled\":false},\"httpProxy\":{\"inbound\":{\"respectForwardedProto\":false},\"outbound\":{\"enabled\":false,\"httpEndpoint\":null,\"httpsEndpoint\":null,\"NoEndpoint\":null}},\"highAvailability\":{\"enabled\":false}}}","source":"ConfigurationApiClient"}
```

### Self-hosted Gateway Version

2.8.1

### Deployment

Self-Managed (YAML/Helm)

### Platform

Other

### Kubernetes Version

Other
